apiVersion: apps/v1
kind: Deployment
metadata:
  name: jason
spec:
  selector:
    matchLabels:
      app: jason
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: jason
        tier: backend
    spec:
      containers:
        - name: jason
          image: jason:0.1
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: ./backend/server.py
            - name: FLASK_RUN_HOST
              value:  0.0.0.0
            - name: FLASK_ENV
              value: production
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
