apiVersion: v1
kind: Service
metadata:
  name: jason
  labels:
    app: jason
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 5002
      targetPort: 5000
  externalIPs:
    - 192.168.64.2  # Minikube on Mac.
    - 172.17.0.4    # Minikube on AWS.
  selector:
    app: jason
    tier: backend
